import org.junit.Test;

import package1.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'pradeep' at '3/12/17 10:49 PM' with Gradle 2.14.1
 *
 * @author pradeep, @date 3/12/17 10:49 PM
 */
public class LibraryTest {
	@Test public void testAppHasAGreeting() {
        Library classUnderTest = new Library();
        assertNotNull("app should have a greeting",
                       classUnderTest.getGreeting());
    }
}
